# -*- coding: utf-8 -*-
"""Exp2_Data_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/184wvRTTNMvZnjqfXqtYw4jIQMw1j4V_m
"""

# ✅ Step 1: Import libraries
import pandas as pd
import numpy as np
import seaborn as sns

# ✅ Step 2: Load clean dataset and create a dirty copy
df = sns.load_dataset("iris")
df_dirty = df.copy()

# ✅ Step 3: Introduce missing values artificially
df_dirty.loc[5:10, 'sepal_length'] = np.nan
df_dirty.loc[15:17, 'species'] = None

# ✅ Step 4: Add a duplicate row
df_dirty = pd.concat([df_dirty, df_dirty.iloc[[0]]], ignore_index=True)

# ✅ Step 5: Add inconsistent string data
df_dirty.loc[0, 'species'] = 'Setosa '
df_dirty.loc[1, 'species'] = 'setosa'
df_dirty.loc[2, 'species'] = 'SETOSA'

# ✅ Show first few dirty rows
print("🔍 Dirty Dataset Preview:")
df_dirty.head(10)

# ✅ 1. Handling Missing Values
print("\nMissing Values Count:")
print(df_dirty.isnull().sum())

# Option 1: Drop rows with missing values
df_cleaned = df_dirty.dropna()

# Option 2: Fill missing values with mean (alternative to dropping)
df_filled = df_dirty.copy()
df_filled['sepal_length'] = df_filled['sepal_length'].fillna(df_filled['sepal_length'].mean())
df_filled['species'] = df_filled['species'].fillna('unknown')

# ✅ 2. Handling Duplicates
print("\nDuplicate Rows Found:", df_filled.duplicated().sum())
df_filled = df_filled.drop_duplicates()

# ✅ 3. Fixing Inconsistent Categorical Data
# Standardize species column: lowercase + strip whitespace
df_filled['species'] = df_filled['species'].str.lower().str.strip()

# ✅ 4. Final Cleaned Data Summary
print("\n✅ Cleaned Data Summary:")
print(df_filled.info())
print("\nUnique species after cleaning:", df_filled['species'].unique())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 4))
sns.heatmap(df_dirty.isnull(), cbar=False, cmap='Reds')
plt.title("Heatmap of Missing Values (Dirty Dataset)")
plt.show()