# -*- coding: utf-8 -*-
"""Exp3_Data_Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qX_6FvjxJILNUDOvRNWLfyivCLWLRaba
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = {'Year': [2010, 2011, 2012, 2013, 2014, 2015, 2016],
        'Sales': [200, 240, 300, 350, 420, 500, 600],
        'Profit': [50, 70, 80, 100, 120, 150, 180]}
df = pd.DataFrame(data)

plt.figure(figsize=(10, 6))
plt.plot(df['Year'], df['Sales'], marker='o', color='b', label='Sales')
plt.plot(df['Year'], df['Profit'], marker='s', color='g', label='Profit')
plt.title('Sales and Profit Over Time')
plt.xlabel('Year')
plt.ylabel('Amount')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 5))
df.plot(kind='bar', x='Year', y=['Sales', 'Profit'], color=['blue', 'green'], figsize=(8,5))
plt.title('Sales and Profit Comparison (2010-2016)')
plt.ylabel('Amount')
plt.xlabel('Year')
plt.show()

plt.figure(figsize=(8, 5))
sns.scatterplot(data=df, x='Sales', y='Profit', hue='Profit', palette='viridis', size='Profit', sizes=(50, 200))
plt.title('Sales vs Profit')
plt.xlabel('Sales')
plt.ylabel('Profit')
plt.show()

plt.figure(figsize=(8, 5))
sns.histplot(df['Sales'], kde=True, color='purple')
plt.title('Sales Distribution')
plt.xlabel('Sales')
plt.ylabel('Frequency')
plt.show()