# -*- coding: utf-8 -*-
"""Exp6_Outlier_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11uzZADKrYSo9BfzH9gA9TW9rfUO73VNG
"""

import numpy as np
import pandas as pd
from scipy.stats import zscore

# Sample dataset
data = {'value': [10, 12, 11, 13, 12, 11, 90, 12, 13, 11, 12]}
df = pd.DataFrame(data)

# Z-score calculation
df['z_score'] = zscore(df['value'])

# Identify outliers (|z| > 3)
df['outlier'] = df['z_score'].abs() > 3
print(df)

from sklearn.datasets import make_blobs
from sklearn.cluster import DBSCAN

# Generate data
X, _ = make_blobs(n_samples=100, centers=1, cluster_std=0.5, random_state=0)
X = np.append(X, [[8, 8], [9, 9]], axis=0)  # Add outliers

# Apply DBSCAN
db = DBSCAN(eps=0.8, min_samples=5).fit(X)

# -1 label indicates outliers
outliers = X[db.labels_ == -1]
print("Detected outliers:\n", outliers)