# -*- coding: utf-8 -*-
"""Exp7_Time_Series_Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kuZ9hxq9SVtscrhtGx31uegqZWmCLHum
"""

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.datasets import get_rdataset

# Load the dataset
data = get_rdataset("AirPassengers").data
df = data.rename(columns={'value': 'passengers'})
df['month'] = pd.date_range(start='1949-01', periods=len(df), freq='M')
df.set_index('month', inplace=True)

# Plot original data
df['passengers'].plot(title="Monthly Airline Passengers", figsize=(10, 4))
plt.show()

# Fit ARIMA model
model = ARIMA(df['passengers'], order=(2, 1, 2))
model_fit = model.fit()

# Forecast next 12 months
forecast = model_fit.forecast(steps=12)

# Plot forecast
df['passengers'].plot(label='Actual', figsize=(10, 4))
forecast.plot(label='Forecast', legend=True)
plt.title("Airline Passengers Forecast")
plt.show()