# -*- coding: utf-8 -*-
"""Exp8_Inferential_Statistics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ueusaGjU1QlUuyAYUzn5dnnpAdZE7tpp
"""

import numpy as np
from scipy import stats
from sklearn.datasets import load_iris

# Load dataset
data = load_iris()
sepal_lengths = data.data[:, 0]

# Calculate confidence interval
mean = np.mean(sepal_lengths)
sem = stats.sem(sepal_lengths)  # standard error of the mean
conf_interval = stats.t.interval(0.95, len(sepal_lengths)-1, loc=mean, scale=sem)

print(f"95% Confidence Interval for Sepal Length: {conf_interval}")

import pandas as pd

# Prepare DataFrame
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target

# Extract samples
setosa = df[df['target'] == 0]['sepal length (cm)']
virginica = df[df['target'] == 2]['sepal length (cm)']

# Perform t-test
t_stat, p_val = stats.ttest_ind(setosa, virginica)
print(f"T-statistic: {t_stat}, P-value: {p_val}")

# Interpretation
if p_val < 0.05:
    print("Reject null hypothesis: Significant difference in means")
else:
    print("Fail to reject null hypothesis: No significant difference")